# Configuración de Netlify para MIT ESTAMPADOS
[build]
  publish = "."
  
# Configuración de Edge Functions

# Edge function para número de pedido secuencial con Netlify Blobs
[[edge_functions]]
  function = "numero-pedido"
  path = "/api/numero-pedido"

# Headers para seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers específicos para la API
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
